/* $Id: locators.h 111747 2025-11-14 16:43:28Z klaus.espenlaub@oracle.com $ */
/** @file
 * Placeholder "locators.h" that wsmousevar.h needs (bad hygiene).
 *
 * It's normally generated by config(8), but see the explanatory
 * comment in vboxguest.ioconf
 */
#define WSMOUSEDEVCF_MUX 0
