# $Id: Makefile.kmk 114014 2026-04-24 12:38:59Z alexander.eichner@oracle.com $
## @file
# Sub-Makefile for the headless frontend.
#

#
# Copyright (C) 2006-2025 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

include $(PATH_SUB_CURRENT)/testcase/Makefile.kmk

#
# Hardened VBoxHeadless.
#
ifdef VBOX_WITH_HARDENING
 PROGRAMS += VBoxHeadlessHardened
 VBoxHeadlessHardened_TEMPLATE = VBoxR3HardenedExe
 VBoxHeadlessHardened_INST.darwin = $(INST_VIRTUALBOX)Contents/Resources/VBoxHeadless.app/Contents/MacOS/
 VBoxHeadlessHardened_DEFS   += $(if $(VBOX_WITH_DRIVERLESS_NEM_FALLBACK),VBOX_WITH_DRIVERLESS_NEM_FALLBACK,)
 VBoxHeadlessHardened_SOURCES = VBoxHeadlessHardened.cpp
 VBoxHeadlessHardened_NAME = VBoxHeadless
 $(call VBOX_SET_VER_INFO_DLL,VBoxHeadlessHardened,VirtualBox Headless Frontend,$(VBOX_WINDOWS_ICON_FILE)) # Version info / description.
endif


#
# VBoxHeadless
#
ifdef VBOX_WITH_HARDENING
 DLLS     += VBoxHeadless
else
 PROGRAMS += VBoxHeadless
endif
VBoxHeadless_TEMPLATE := $(if $(VBOX_WITH_HARDENING),VBoxMainClientDll,VBoxMainClientSignedExe)
ifndef VBOX_WITH_HARDENING
 VBoxHeadless_INST.darwin = $(INST_VIRTUALBOX)Contents/Resources/VBoxHeadless.app/Contents/MacOS/
endif
VBoxHeadless_DEFS     += $(if $(VBOX_WITH_RECORDING),VBOX_WITH_RECORDING,)
VBoxHeadless_INCS      = \
	$(VBOX_GRAPHICS_INCS) \
	../Common
VBoxHeadless_SOURCES   = \
	VBoxHeadless.cpp \
	../Common/PasswordInput.cpp
ifdef VBOX_WITH_GUEST_PROPS
 VBoxHeadless_DEFS    += VBOX_WITH_GUEST_PROPS
endif

#
# Parfait fails with an error that ../MacOS can't be accessed while standard clang has no problem with it.
# As we don't want to run the output just omit the -rpath arguments to make it build
#
ifndef VBOX_WITH_PARFAIT
 VBoxHeadless_LDFLAGS.darwin = \
 	$(if $(VBOX_WITH_HARDENING) \
 		,-install_name $(VBOX_DYLD_EXECUTABLE_PATH)/VBoxHeadless.dylib \
 		,-rpath @executable_path/../../../../MacOS)
endif

ifdef VBOX_WITH_HARDENING
 $(call VBOX_SET_VER_INFO_DLL,VBoxHeadless,VirtualBox Headless Frontend (dll),$(VBOX_WINDOWS_ICON_FILE)) # Version info / description.
else
 $(call VBOX_SET_VER_INFO_EXE,VBoxHeadless,VirtualBox Headless Frontend,$(VBOX_WINDOWS_ICON_FILE)) # Version info / description.
endif

ifeq ($(KBUILD_TARGET),darwin)

 INSTALLS += VBoxHeadless.app
 VBoxHeadless.app_INST = $(INST_VIRTUALBOX)Contents/Resources/VBoxHeadless.app/Contents/
 VBoxHeadless.app_MODE = 644
 VBoxHeadless.app_SOURCES = \
 	VM-PkgInfo=>PkgInfo \
 	$(VBoxHeadless.app_0_OUTDIR)/VM-Info.plist=>Info.plist
 ifdef VBOX_WITH_INTNET_SERVICE_IN_R3
  VBoxHeadless.app_SYMLINKS = \
  	XPCServices=>../../../XPCServices
 endif

 $$(VBoxHeadless.app_0_OUTDIR)/VM-Info.plist: $(PATH_SUB_CURRENT)/VM-Info.plist $(VBOX_VERSION_MK) | $$(@D)/
	$(call MSG_GENERATE,VBoxHeadless.app,$<,$@)
	$(QUIET)$(RM) -f $@
	$(QUIET)$(SED) \
		-e 's+@VBOX_VERSION_STRING@+$(VBOX_VERSION_STRING)+g' \
		-e 's+@VBOX_VERSION_MAJOR@+$(VBOX_VERSION_MAJOR)+g' \
		-e 's+@VBOX_VERSION_MINOR@+$(VBOX_VERSION_MINOR)+g' \
		-e 's+@VBOX_VERSION_BUILD@+$(VBOX_VERSION_BUILD)+g' \
		-e 's+@VBOX_VENDOR@+$(VBOX_VENDOR)+g' \
		-e 's+@VBOX_PRODUCT@+$(VBOX_PRODUCT)+g' \
		-e 's+@VBOX_C_YEAR@+$(VBOX_C_YEAR)+g' \
		--output $@ $<
endif # darwin

include $(FILE_KBUILD_SUB_FOOTER)

